Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Vetalll-pc\Documents\Projects\Python\antbl2\app\Ui.py", line 44, in _lop
    captcha_button = self.logic.check_captcha()
  File "C:\Users\Vetalll-pc\Documents\Projects\Python\antbl2\app\BotCaptchaLoigic.py", line 23, in check_captcha
    return self._check_group_captcha(screenshot_image)
  File "C:\Users\Vetalll-pc\Documents\Projects\Python\antbl2\app\BotCaptchaLoigic.py", line 54, in _check_group_captcha
    result = self.group_parser.parse_image(screenshot_image)
  File "C:\Users\Vetalll-pc\Documents\Projects\Python\antbl2\app\parsers\GroupDialogParser.py", line 67, in parse_image
    target_y = int(header_loc[0][0] + 125 + target_loc[0])
TypeError: only size-1 arrays can be converted to Python scalars